# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x0borbit.serve\"\x80\x01\n\rDecideRequest\x12\t\n\x01x\x18\x01 \x03(\x02\x12\x12\n\nn_features\x18\x02 \x01(\x05\x12\x10\n\x08\x65\x64ge_src\x18\x03 \x03(\x05\x12\x10\n\x08\x65\x64ge_dst\x18\x04 \x03(\x05\x12\x19\n\x11runnable_node_ids\x18\x05 \x03(\x05\x12\x11\n\tavailable\x18\x06 \x03(\x05\"S\n\x0e\x44\x65\x63ideResponse\x12\x14\n\x0cstage_action\x18\x01 \x01(\x05\x12\x14\n\x0c\x61lloc_action\x18\x02 \x01(\x05\x12\x15\n\rstage_node_id\x18\x03 \x01(\x05\x32N\n\tScheduler\x12\x41\n\x06\x44\x65\x63ide\x12\x1a.orbit.serve.DecideRequest\x1a\x1b.orbit.serve.DecideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIDEREQUEST']._serialized_start=33
  _globals['_DECIDEREQUEST']._serialized_end=161
  _globals['_DECIDERESPONSE']._serialized_start=163
  _globals['_DECIDERESPONSE']._serialized_end=246
  _globals['_SCHEDULER']._serialized_start=248
  _globals['_SCHEDULER']._serialized_end=326
# @@protoc_insertion_point(module_scope)
